// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3Xx_VWGBPQcUT-nlrGk059VuRIycRHQ',
    appId: '1:191033845677:web:eeb5de7759855c97d06324',
    messagingSenderId: '191033845677',
    projectId: 'ben-kimim-3b615',
    authDomain: 'ben-kimim-3b615.firebaseapp.com',
    storageBucket: 'ben-kimim-3b615.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDI8dvxvdCu-y4KNZKGZIngavXZI8kRmw',
    appId: '1:191033845677:android:b0d5720fd4b3be35d06324',
    messagingSenderId: '191033845677',
    projectId: 'ben-kimim-3b615',
    storageBucket: 'ben-kimim-3b615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGaA0VB7rv7FA_NUwctrErcOsLQ0CxhVk',
    appId: '1:191033845677:ios:f0cccf6e8b778534d06324',
    messagingSenderId: '191033845677',
    projectId: 'ben-kimim-3b615',
    storageBucket: 'ben-kimim-3b615.firebasestorage.app',
    iosBundleId: 'com.example.benKimim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGaA0VB7rv7FA_NUwctrErcOsLQ0CxhVk',
    appId: '1:191033845677:ios:f0cccf6e8b778534d06324',
    messagingSenderId: '191033845677',
    projectId: 'ben-kimim-3b615',
    storageBucket: 'ben-kimim-3b615.firebasestorage.app',
    iosBundleId: 'com.example.benKimim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa3Xx_VWGBPQcUT-nlrGk059VuRIycRHQ',
    appId: '1:191033845677:web:99e4d23adba7d6f2d06324',
    messagingSenderId: '191033845677',
    projectId: 'ben-kimim-3b615',
    authDomain: 'ben-kimim-3b615.firebaseapp.com',
    storageBucket: 'ben-kimim-3b615.firebasestorage.app',
  );
}
